version: '3.8'

services:
  app:
    build: .
    environment:
      - DB_HOST=172.31.0.1
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventos
    ports:
      - "5432:5432"
