name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./homolog

      - name: Update code
        run: git pull

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install pm2
        run: npm install -g pm2

      - name: Deploy the API with pm2
        run: pm2 start ecosystem.config.js
        working-directory: ./homolog

      - name: Down all containers
        run: docker compose down

      - name: Remove all img
        run: docker image prune -f

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Verify services are running
        run: docker ps -a
